<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Autofac"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\LoreBank.Bank.Application\LoreBank.Bank.Application.csproj"/>
        <ProjectReference Include="..\LoreBank.Bank.Domain\LoreBank.Bank.Domain.csproj"/>
        <ProjectReference Include="..\LoreBank.SharedKernel.Infrastructure\LoreBank.SharedKernel.Infrastructure.csproj"/>
    </ItemGroup>

</Project>
