// <auto-generated />
using System;
using LoreBank.Ledger.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoreBank.Ledger.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LedgerDbContext))]
    [Migration("20260905142533_InitialLedgerSchema")]
    partial class InitialLedgerSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ledger")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoreBank.Ledger.Domain.Aggregates.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("journal_entries", "ledger");
                });

            modelBuilder.Entity("LoreBank.Ledger.Domain.Aggregates.JournalEntry", b =>
                {
                    b.OwnsMany("LoreBank.Ledger.Domain.ValueObjects.JournalLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Account")
                                .IsRequired()
                                .HasMaxLength(42)
                                .HasColumnType("character varying(42)")
                                .HasColumnName("account_ref");

                            b1.Property<string>("Direction")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("character varying(6)")
                                .HasColumnName("direction");

                            b1.Property<Guid>("journal_entry_id")
                                .HasColumnType("uuid");

                            b1.HasKey("id");

                            b1.HasIndex("journal_entry_id");

                            b1.ToTable("journal_lines", "ledger");

                            b1.WithOwner()
                                .HasForeignKey("journal_entry_id");

                            b1.OwnsOne("LoreBank.SharedKernel.Domain.ValueObjects.Money", "Amount", b2 =>
                                {
                                    b2.Property<Guid>("JournalLineid")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric")
                                        .HasColumnName("amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("currency");

                                    b2.HasKey("JournalLineid");

                                    b2.ToTable("journal_lines", "ledger");

                                    b2.WithOwner()
                                        .HasForeignKey("JournalLineid");
                                });

                            b1.Navigation("Amount")
                                .IsRequired();
                        });

                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
