<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="coverlet.collector">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="FluentAssertions" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="NUnit" />
        <PackageReference Include="NUnit3TestAdapter" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\LoreBank.Ledger.Application\LoreBank.Ledger.Application.csproj" />
        <ProjectReference Include="..\LoreBank.SharedKernel.Test.Infrastructure\LoreBank.SharedKernel.Test.Infrastructure.csproj" />
    </ItemGroup>

</Project>
