<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="FluentAssertions" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="NUnit" />
        <PackageReference Include="NUnit3TestAdapter" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\LoreBank.Bank.Domain\LoreBank.Bank.Domain.csproj" />
        <ProjectReference Include="..\LoreBank.Bank.Application\LoreBank.Bank.Application.csproj" />
    </ItemGroup>

</Project>
