<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.4">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="FluentAssertions" Version="7.2.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
        <PackageReference Include="NUnit" Version="4.4.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="6.1.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\LoreBank.Bank.Domain\LoreBank.Bank.Domain.csproj" />
        <ProjectReference Include="..\LoreBank.Bank.Application\LoreBank.Bank.Application.csproj" />
    </ItemGroup>

</Project>
